name: Maven Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Extract version from tag
        id: get_version
        run: echo "##[set-output name=version;]$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')"
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Attach artifacts to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/441homework-1.0-SNAPSHOT.jar
          asset_name: 441homework-1.0-SNAPSHOT-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive
